# Generated by Django 5.0.2 on 2024-03-14 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ReservationID', models.AutoField(primary_key=True, serialize=False)),
                ('BookingDate', models.DateField()),
                ('PartySize', models.IntegerField()),
                ('SpecialRequests', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('MobileNumber', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ReservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='firstapp.reservation')),
                ('Name', models.CharField(max_length=255)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.customer'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('Comment', models.TextField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.customer')),
                ('ReservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.reservation')),
            ],
        ),
    ]
