# Generated by Django 5.0.2 on 2024-03-30 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='CustomerID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='CustomerID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ReservationID',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ReservationID',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='Capacity',
        ),
        migrations.AddField(
            model_name='booking',
            name='BookingDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='BookingID',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='SpecialRequests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Description',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='NoOfFourTables',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='NoOfSixTables',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='NoOfTwoTables',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='RestaurantID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='firstapp.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='Comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='Rating',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
