# Generated by Django 5.0.2 on 2024-03-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_reservation_customerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='BookingID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
