# Generated by Django 5.0.2 on 2024-03-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_booking_bookingid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='BookingID',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='RestaurantID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ReviewID',
        ),
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
