# Generated by Django 5.0 on 2024-03-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='num_ratings',
            field=models.IntegerField(default=0, max_length=99999),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
