# Generated by Django 5.0 on 2024-03-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_restaurant_num_ratings_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Max_NoOfFourTables',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Max_NoOfSixTables',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Max_NoOfTwoTables',
            field=models.IntegerField(null=True),
        ),
    ]
