# Generated by Django 5.0 on 2024-04-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_remove_booking_date_remove_booking_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='RestaurantID',
            new_name='Restaurant',
        ),
        migrations.AddField(
            model_name='booking',
            name='Restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.restaurant'),
        ),
    ]
