# Generated by Django 5.0 on 2024-04-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_rename_restaurantid_review_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='NoOfFourTables',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='NoOfSixTables',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='NoOfTwoTables',
            field=models.IntegerField(null=True),
        ),
    ]
