# Generated by Django 5.0 on 2024-04-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_booking_nooffourtables_booking_noofsixtables_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='datetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
