# Generated by Django 5.0.2 on 2024-04-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='num_ratings',
            field=models.IntegerField(default=0, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
